### ISSUE TITLE
Create java class that implement FederatedCacheStore.

### ISSUE THREAD

**Issue by augustocmleal** [truzzt/FederatedCatalog#11]
Related to user story #10

**Comment by schoenenberg** [comment]
Upstream related to https://github.com/eclipse-edc/FederatedCatalog/issues/9

**Comment by augustocmleal** [comment]
https://github.com/eclipse-edc/FederatedCatalog/blob/main/spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/FederatedCacheStore.java
